### ISSUE TITLE
Menu issue on Flatpak on Sublime 3.2.2 build 3211

### ISSUE THREAD

**Issue by Efadd** [msh-shiplu/CodeSpace#26]
**Describe the bug**
When I select an option to set up GEM 0.94, it opens the dialog 2 menu options up, i.e. trying to set the Username opens the box to set the server address

**Describe which task within SublimeText you were do ing when this bug occur.**
Nothing, just opened it

**Content of SublimeText console**
Instruction: in SublimeText, click View --> Show Console, and copy the error message there, if there's any, and paste it here.
startup, version: 3211 linux x64 channel: stable
executable: /app/extra/sublime_text/sublime_text
working dir: /home/efadd
packages path: /home/efadd/.var/app/com.sublimetext.three/config/sublime-text-3/Packages
state path: /home/efadd/.var/app/com.sublimetext.three/config/sublime-text-3/Local
zip path: /app/extra/sublime_text/Packages
zip path: /home/efadd/.var/app/com.sublimetext.three/config/sublime-text-3/Installed Packages
ignored_packages: ["Vintage"]
pre session restore time: 0.329186
startup time: 0.664755
first paint time: 0.674235
reloading plugin Default.arithmetic
reloading plugin Default.auto_indent_tag
reloading plugin Default.block
reloading plugin Default.colors
reloading plugin Default.comment
reloading plugin Default.convert_color_scheme
reloading plugin Default.convert_syntax
reloading plugin Default.copy_path
reloading plugin Default.detect_indentation
reloading plugin Default.echo
reloading plugin Default.exec
reloading plugin Default.fold
reloading plugin Default.font
reloading plugin Default.goto_line
reloading plugin Default.history_list
reloading plugin Default.indentation
reloading plugin Default.install_package_control
reloading plugin Default.kill_ring
reloading plugin Default.mark
reloading plugin Default.new_templates
reloading plugin Default.open_context_url
reloading plugin Default.open_in_browser
reloading plugin Default.pane
reloading plugin Default.paragraph
reloading plugin Default.paste_from_history
reloading plugin Default.profile
reloading plugin Default.quick_panel
reloading plugin Default.rename
reloading plugin Default.run_syntax_tests
reloading plugin Default.save_on_focus_lost
reloading plugin Default.scroll
reloading plugin Default.set_unsaved_view_name
reloading plugin Default.settings
reloading plugin Default.show_scope_name
reloading plugin Default.side_bar
reloading plugin Default.sort
reloading plugin Default.switch_file
reloading plugin Default.symbol
reloading plugin Default.transform
reloading plugin Default.transpose
reloading plugin Default.ui
reloading plugin CSS.css_completions
reloading plugin Diff.diff
reloading plugin HTML.encode_html_entities
reloading plugin HTML.html_completions
reloading plugin ShellScript.ShellScript
reloading plugin auto-save.auto_save
reloading plugin Package Control.plugin
reloading plugin GEMStudent.GEMStudent
plugins loaded
Package Control: All specified packages up-to-date!
Error making request
Error making request
reloading plugin GEMStudent.GEMStudent
reloading plugin GEMStudent.GEMStudent

**Additional context**

**Comment by Efadd** [comment]
https://github.com/msh-shiplu/CodeSpace/assets/84989803/861f9c7d-698c-44a1-9f70-adfd330e1d86

**Comment by msh-shiplu** [comment]
> When I select an option to set up GEM 0.94, it opens the dialog 2 menu options up, i.e. trying to set the Username opens the box to set the server address

I am not sure I get issue. Could you please explain a bit more?

**Comment by Efadd** [comment]
When I try to check my set-up of GEM, the wrong menu opens from the dropdown. I added the video to try and help.

**Comment by msh-shiplu** [comment]
The video just shows the github comment nothing else. Could you please make a video again and upload?

**Comment by Efadd** [comment]
https://github.com/msh-shiplu/CodeSpace/assets/84989803/57973591-aae7-4077-9a01-8217d03350f9

Sorry, I'd reincoded the wrong video

**Comment by Efadd** [comment]
Ok, further updates to Sublime or Debian as a whole fixed it
